name: craft
description: Provides Oauth clients with token auto-refresh support, queueing
  requests, offline support
version: 1.0.0
homepage: https://craftlib.com
repository: https://github.com/stelynx/craft
environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^6.0.0
  hive: ^2.2.3
  http: ^0.13.5
  meta: ^1.8.0
  synchronized: ^3.0.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  kamino_flutter_lints: null
  mockito: ^5.3.2
  test: ^1.16.0
