name: Lint 

on: push

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2.4.0
        with:
          channel: "stable"

      - name: Lint
        run: |
          flutter pub get
          flutter analyze
