name: Publish to pub.dev

on:
  release: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install Flutter
        uses: subosito/flutter-action@v2.4.0
        with:
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get

      - name: Setup Pub Credentials
        env:
          PUB_DEV_CREDENTIALS_JSON: ${{ secrets.PUB_DEV_CREDENTIALS_JSON }}
        run: echo "$PUB_DEV_CREDENTIALS_JSON" | base64 --decode > $XDG_CONFIG_HOME/dart/pub-credentials.json

      - name: Check Publish Warnings
        run: pub publish --dry-run

      - name: Publish Package
        run: pub publish -f
