name: Test 

on: push

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2.4.0
        with:
          channel: "stable"

      - name: Register all dart files
        uses: stelynx/dart-full-coverage@v1.1.1
        with:
          package: craft

      - name: Test
        run: |
          flutter pub get
          flutter test --coverage .

      - name: Upload codecov report
        uses: codecov/codecov-action@v3
